// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndvxuwtzpzwbyunbqqcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kdnh1d3R6cHp3Ynl1bmJxcWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODA1ODMsImV4cCI6MjA2NTA1NjU4M30.s7hnLjW6K8Q4fiDCchnpit4oeb2Z4pslHaZMzuAjeLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);